######################## default configuration ####################
baseURL = "https://demo.gethugothemes.com/liva/examplesite/"
languageCode = "en-us"
title = "MIND AND MUSCLE"
theme = "liva-hugo"
summaryLength = "10"
pagination.pagerSize = 6
disqusShortname = ""
