######################## default configuration ####################
baseURL = "http://localhost:1313/"
languageCode = "en-us"
title = "MIND AND MUSCLE"
theme = "liva-hugo"
summaryLength = "230"
pagination.pagerSize = 6
disqusShortname = ""
