name = "MIND AND MUSCLE"
license = "MIT"
licenselink = "https://github.com/gethugothemes/liva-hugo/blob/master/LICENSE"
description = "MIND AND MUSCLE."
homepage = "https://gethugothemes.com/products/liva-hugo/"
demosite = "https://demo.gethugothemes.com/liva"
tags = ['landing-page', 'fast', 'light', 'white', 'modern', 'themefisher', 'hugo-theme', 'hugo-templates', 'bootstrap', 'blog', 'responsive', 'clean', 'simple', 'creative', 'contact-form', 'custom-themes', 'mobile', 'minimalistic', 'gethugothemes', 'resume', 'portfolio', 'google analytics', 'customizable', 'flexbox', 'presentation', 'product', 'theme', 'typography']
features = ['bootstrap','responsive']
min_version = "0.147.2"

[author]
  name = "Gethugothemes"
  homepage = "https://gethugothemes.com/"
